export const ErrorCode = {
  COMMON: {
    INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',
    UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
    FORBIDDEN: 'COMMON.FORBIDDEN',
    NOT_FOUND: 'COMMON.NOT_FOUND',
    RATE_LIMITED: 'COMMON.RATE_LIMITED',
  },
  VALIDATION: {
    FAILED: 'VALIDATION.FAILED',
    REQUIRED: 'VALIDATION.REQUIRED',
    INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
    INVALID_TYPE: 'VALIDATION.INVALID_TYPE',
    TOO_SHORT: 'VALIDATION.TOO_SHORT',
    TOO_LONG: 'VALIDATION.TOO_LONG',
    TOO_SMALL: 'VALIDATION.TOO_SMALL',
    TOO_BIG: 'VALIDATION.TOO_BIG',
    INVALID_UUID: 'VALIDATION.INVALID_UUID',
    INVALID_DATE: 'VALIDATION.INVALID_DATE',
    FUTURE_DATE: 'VALIDATION.FUTURE_DATE',
    POSITIVE_REQUIRED: 'VALIDATION.POSITIVE_REQUIRED',
    NON_NEGATIVE_REQUIRED: 'VALIDATION.NON_NEGATIVE_REQUIRED',
    INTEGER_REQUIRED: 'VALIDATION.INTEGER_REQUIRED',
    ARRAY_MIN: 'VALIDATION.ARRAY_MIN',
    NOT_EMPTY: 'VALIDATION.NOT_EMPTY',
  },
  VOUCHER: {
    NOT_FOUND: 'VOUCHER.NOT_FOUND',
    DUPLICATE_NUMBER: 'VOUCHER.DUPLICATE_NUMBER',
    ALREADY_DELETED: 'VOUCHER.ALREADY_DELETED',
  },
  WAREHOUSE: {
    NOT_FOUND: 'WAREHOUSE.NOT_FOUND',
    INACTIVE: 'WAREHOUSE.INACTIVE',
  },
  ITEM: {
    NOT_FOUND: 'ITEM.NOT_FOUND',
  },
} as const;

type ErrorCodeValues<T> = T extends Record<string, infer V>
  ? V extends string
    ? V
    : ErrorCodeValues<V>
  : never;

export type ErrorCodeType = ErrorCodeValues<typeof ErrorCode>;
